### ISSUE TITLE
Implement allow users change password via UI

### ISSUE THREAD

**Issue by juanpicado** [verdaccio/ui#1]
#### My reason:

Currently, there is no such interface, any user should be able to update the password. 

####  Config file:	

No config changes need it.

Depends on https://github.com/verdaccio/verdaccio-htpasswd/issues/32
Depends on https://github.com/verdaccio/verdaccio/issues/392

**Comment by priscilawebdev** [comment]
if anyone want to do this task..please feel free!

**Comment by agar23** [comment]
@priscilawebdev  I would like to take this up? any guidance from work done already?

**Comment by juanpicado** [comment]
@agar23 let's wait for now. I'm working on https://github.com/verdaccio/verdaccio/pull/1546 which will clarify many things.

**Comment by priscilawebdev** [comment]
@juanpicado any update on this? :)

**Comment by priscilawebdev** [comment]
@juanpicado is actively working on this and he will soon provide an endpoint.
