### ISSUE TITLE
If package is not found, the website does not render 404 page

### ISSUE THREAD

**Issue by juanpicado** [verdaccio/ui#100]
**Describe the bug**

The website does not render the page 404 whether package is not found in the storage.

**To Reproduce**
1. Use latest verdaccio
2. Update conf to remove any `proxy `prop in packages
3. Publish any package with dependencies
4. Reload the page
5. Browse your package to dependencies
6. Click in the dependency (open dev tools and see the HTTP 404)
7. Nothing happens

**Expected behavior**

If user clicks on any dependency and it is not found, we should display 404

**Screenshots**

![Kapture 2019-07-12 at 15 38 48](https://user-images.githubusercontent.com/558752/61132236-3e259200-a4bb-11e9-9e1f-3cbfa6ba8491.gif)

**Configuration File (cat ~/.config/verdaccio/config.yaml)** 

**Additional context**

This will requires a unit test proving this works properly.

**Comment by DanielRuf** [comment]
> This will requires a unit test proving this works properly.

Did you check my BDD test setup? Why not use E2E testing for such cases? Normal unit tests won't catch this.

**Comment by juanpicado** [comment]
@DanielRuf It is on the queue, but I think we are gonna create a roadmap, so we can put all these things. cc: @sergiohgz 

Before was suggested https://www.cypress.io/ but I did not have time to look into it and wether make sense in our workflow.
