### ISSUE TITLE
i18n at UI 

### ISSUE THREAD

**Issue by juanpicado** [verdaccio/ui#102]
**Is your feature request related to a problem? Please describe.**

Verdaccio is in English by default, but I want to change that. I would like to have multiple languages via configuration.

**Describe the solution you'd like**

I want UI (perhaps backend) in multiple languages. I would like to take advance of crowdin platform for this. 

**Describe alternatives you've considered**

I am not clear at this stage, perhaps

https://lingui.js.org/

Or similar things.

**Comment by DanielRuf** [comment]
lingui seems a bit weird (we have to wrap the translatable strings in another component) https://lingui.js.org/ref/react.html#ref-react

https://github.com/i18next/react-i18next looks more familiar with translation implementations in other frameworks which use some `t()` or `_()` helper methods.

**Comment by DanielRuf** [comment]
https://codesandbox.io/s/1zxox032q

**Comment by juanpicado** [comment]
@DanielRuf seems nice, pretty much what I've seen in others by far. We need to run some test before choose anyone and see how might works with Crowdin.

**Comment by juanpicado** [comment]
https://link.medium.com/08QfpgvAsZ

**Comment by DanielRuf** [comment]
Intl is basically for helper methods as it formats dates, currency, time and a few more but is not intendend to implement i18n for a whole application.

Let's not reinvent the wheel and not do it from scratch.

**Comment by juanpicado** [comment]
:-) sorry I did not have any better place to save the article 😊

**Comment by DanielRuf** [comment]
Ah okay =)

**Comment by juanpicado** [comment]
Intersting conversation and related https://github.com/gatsbyjs/rfcs/pull/42

**Comment by juanpicado** [comment]
I will work on this.

**Comment by juanpicado** [comment]
My strategy:

- fetch data from crowdin
- create some sort of data for UI
- prepare data for i18n react plugin 
- prepare build
- add new config param for chosen language
- build some test 
- cross fingers all works 
- new translations will be available to download only those has rights and periodically (later on we can automate this)
- I want crowdin be the central point for all translations

**Comment by priscilawebdev** [comment]
Do you guys (@verdaccio/core-team) mind if I take over? I would love to implement i18n here

**Comment by DanielRuf** [comment]
You can work on it @priscilawebdev =)

**Comment by juanpicado** [comment]
@priscilawebdev ignore crowdin as I rewrote my thoughts above, find a different strategy, for now location files should be hosted on this repo.
