### ISSUE TITLE
Cannot run dev server without commenting some lines

### ISSUE THREAD

**Issue by sergiohgz** [verdaccio/ui#105]
**Describe the bug**
When running dev server, it should compile without errors and reload efficently the browser. At the moment, it is not finding a file called `app` (extension could be js or ts, it doesn't matter) in `src` folder. The file is required by `src/index.tsx`, line 25, by `module.hot.accept` function.
We can bypass this bug by commenting lines 25 and 27 (function call, not callback), but then the browser (tested in Chrome 75.0.3770.100) says that react-hot-dom is not detected and never reload because it will ignore updates from unaccepted modules (every file will be)

**To Reproduce**
1. yarn install --frozen-lockfile
2. yarn dev
3. Wait until console says `WAIT Compiling...`
4. Look at the error

**Expected behavior**
Compile without errors. I don't know if hot reload is caused by this.

**Screenshots**
![running_dev_server](https://user-images.githubusercontent.com/14012309/61212800-8f27c700-a703-11e9-88ba-5665f07a19f4.png)
--- 
![react-hot-loader_not_detected](https://user-images.githubusercontent.com/14012309/61212857-b1b9e000-a703-11e9-928a-f6ec82d10f4e.png)
---
![ignoring_reload_event](https://user-images.githubusercontent.com/14012309/61212894-c39b8300-a703-11e9-9406-776e0067af67.png)

**Docker || Kubernetes (please complete the following information):** Not using Docker

**Configuration File (cat ~/.config/verdaccio/config.yaml)** Default config file in development cycle

**Debugging output**
 - `$ NODE_DEBUG=request verdaccio` display request calls (verdaccio <--> uplinks) -> Not necessary
 - `$ DEBUG=express:* verdaccio` enable extreme verdaccio debug mode (verdaccio api) -> Not necessary
 - `$ npm -ddd` prints:
```
npm info it worked if it ends with ok
npm verb cli [ '/usr/local/bin/node', '/opt/npm-global/bin/npm', '-ddd' ]
npm info using npm@6.9.0
npm info using node@v12.6.0
npm verb config Skipping project config: /home/sergio/.npmrc. (matches userconfig)
```
 - `$ npm config get registry` prints: http://localhost:4873/ (Verdaccio instance as cache)
 - Additional `$ yarn version`: 1.17.3

**Additional context**
This happens everytime, doesn't matter if you download the repo from scratch

**Comment by sergiohgz** [comment]
The part of not working Hot Reload is described better in #62

**Comment by DanielRuf** [comment]
Did we already fix this somehow or is it still a todo?
