### ISSUE TITLE
Refactor suggested styles

### ISSUE THREAD

**Issue by sergiohgz** [verdaccio/ui#107]
This issue will track several CSS changes we see across PRs relatives to issue #97 (like #104).

#### Discovered in #104 
- [ ] `src/components/Author/styles.ts#L7` - use `fontWeight.bold` from `utils/styles/sizes`
- [ ] `src/components/Developers/styles.ts#L23` - use `fontWeight.bold` from `utils/styles/sizes`
- [ ] `src/components/Dist/styles.ts#L11` - use `fontWeight.bold` from `utils/styles/sizes`
- [ ] `src/components/Engines/styles.ts#L10` - repetition of Heading component styles
- [ ] `src/components/Header/styles.ts#L52` - `padding: '0 5px'` to be consistent (also look for others)
- [ ] `src/components/Package/styles.ts#L39` - `margin: '2px 10px 0 0'` to be consistent (also look for others)
- [ ] `src/components/Package/styles.ts#L47` - `margin: '0 5px 0 0'` to be consistent (also look for others)
- [ ] `src/components/Layout/Layout.tsx#L5` - `#ffffff` should be reusable

---

**Note:** This description will be updated with more information when we discover other cases :wink:

**Comment by griffithtp** [comment]
@sergiohgz @juanpicado can close this now? :)

**Comment by sergiohgz** [comment]
I prefer to have it opened and fix them in a near future.

**Comment by abc516** [comment]
Hi @sergiohgz @juanpicado I'd be interested in tackling some of the issues posted. Which of them are still relevant?

**Comment by hugoazevedosoares** [comment]
I could no find the file utils/styles/sizes on branch master. Is that on a diferent branch?

**Comment by juanpicado** [comment]
@hugoazevedosoares the ticket is old, locations might be different by know.

**Comment by hugoazevedosoares** [comment]
Thanks @juanpicado . This is still relevant? If so I can help :)

**Comment by juanpicado** [comment]
Agree, it is outdated. But you can contribute in other areas https://github.com/verdaccio/ui/labels/good%20first%20issue if you like, either linting or improve test, you decide 👍
