### ISSUE TITLE
Font Pathing issue in Master

### ISSUE THREAD

**Issue by NathanaelA** [verdaccio/ui#108]
**Describe the bug**
I pulled the latest UI master as of today (2019-07-15) and ran the build script; then linked the ui properly up to my copy of Verdaccio.

However, several of the fonts are showing in brave as this:
`https://npm.proplugins.org/-/static/ToReplaceByVerdaccio/-/staticfonts/roboto-latin-400.woff2`
Which of course is broken url.   Coming from a CSS File:
`referer: https://npm.proplugins.org/-/static/0.style.026be7a5bc0c57143eb2.css`

   I created a symlink path on my local server to solve this issue; but whatever is creating the path to load the .woff2 files is broken.

**To Reproduce**
1. Install UI from 4.0-master in Verdaccio
2. Open dev tools; network tab.
3. Load the Verdaccio instance

**Expected behavior**
No broken links.

**Screenshots**

![image](https://user-images.githubusercontent.com/850871/61345492-08660d80-a81b-11e9-93fb-952348e87387.png)

Please note the path; it is a 304; because I did create a path/symlink back to the static fonts folder; so that it can be resolved...

**Comment by DanielRuf** [comment]
Related:
https://github.com/verdaccio/ui/blame/6b5d0b7e2e37c4f0324b17b5794a01ebec49a71e/tools/webpack.prod.config.babel.js#L51
https://github.com/verdaccio/ui/blame/50664dc0088ee95df83cbf00b8d6a321de2135cf/tools/webpack.config.js#L10-L11
