### ISSUE TITLE
Using React Hooks (Refactoring, New Components)

### ISSUE THREAD

**Issue by juanpicado** [verdaccio/ui#116]
**Is your feature request related to a problem? Please describe.**

React Hooks is a topic we wanna to raise up in order to keep modernize the project. Currently we rely on Classes components and Stateless components.

**Describe the solution you'd like**

Since this is a new topic for the big majority, here https://github.com/verdaccio/ui/pull/115 the first step. 

**Describe alternatives you've considered**

It is not mandatory to refactor all existing components, but if someone is willing to levep up the React skills, go ahead, but here some rules for this

- If there is not test, it must included it.
- If the test already exist, you will need to either refactor it or update it.
- One component (refactoring/new) peer PR 🙏 
- All test must pass (soon also with Browserstack https://github.com/verdaccio/ui/pull/111)
- Don't be afraid to extract components if you consider the chosen one can be improved, ask for suggestions in our chat for guidance.

**Additional context**

- We have updated to React `16.9.0` so, many issues related with Enzyme now are gone. There are some limitations with `shallow` rendering, so be aware of it. https://github.com/airbnb/enzyme/issues/2011
- We added `@testing-library/react` if someone wants to experiments with it. But we keep Enzyme as a main testing tool.
- `eslint-plugin-react-hooks` was added for help linting the new components.

If you have any questions, ask http://chat.verdaccio.org `#question` channel.  Or if you have suggestions feel free to drop it here. This is a long term ticket (either called story) so, here the policy is **first come first served**, just PR and we will help with the code review.

**Comment by priscilawebdev** [comment]
> We added @testing-library/react
Me when I saw it: 😍

**Comment by priscilawebdev** [comment]
I will do this task 😉

**Comment by gagandeepp** [comment]
@priscilawebdev  can I work on this too??

@juanpicado

**Comment by priscilawebdev** [comment]
@gagandeepp yes sure... please just let me know which components you would to refactor 🙃

**Comment by gagandeepp** [comment]
@priscilawebdev  I will be refactoring login module

**Comment by nutboltu** [comment]
@priscilawebdev and @juanpicado Can I also work on this issue?

**Comment by juanpicado** [comment]
go ahead @nutboltu 👍

**Comment by agar23** [comment]
@juanpicado any components I can take up?

**Comment by priscilawebdev** [comment]
@agar23 thank you for reaching out! What do you think about the component "PackageList"? it would be really nice to have it as a Functional component 😉

**Comment by agar23** [comment]
> @agar23 thank you for reaching out! What do you think about the component "PackageList"? it would be really nice to have it as a Functional component 😉

sounds good! I will take a stab at it and submit a PR.

**Comment by juanpicado** [comment]
@priscilawebdev do we have something else here to be done? we have done plenty of it already 🚀

**Comment by priscilawebdev** [comment]
@juanpicado sorry I could not answer your question in the past days. I've just checked and we still have to convert the following components:

- Repository
- Search
- Login (LoginModal)
- ActionBar

**Comment by agar23** [comment]
> @juanpicado sorry I could not answer your question in the past days. I've just checked and we still have to convert the following components:
> 
> * Repository
> * Search
> * Login (LoginModal)
> * ActionBar

I can take up Login & ActionBar if possible.

**Comment by juanpicado** [comment]
go ahead @agar23  ! Thanks for the help.

**Comment by priscilawebdev** [comment]
I believe we have achieved it today!  thank you for all the contributions 💪🙂
