### ISSUE TITLE
Download tarball on Firefox and Edge doesn't work properly

### ISSUE THREAD

**Issue by lukebelliott** [verdaccio/ui#119]
**Describe the bug**
Download tarball on Firefox and Edge doesn't open "Open with" dialog / save to default location.

**To Reproduce**
1. Go to package page.
2. Click on 'Download tarball'

**Expected behavior**
"Open with" dialog should open (as in Chrome) / save to default location.

**Configuration File (cat ~/.config/verdaccio/config.yaml)**
Using default config.

**Environment information**
Running dev:start of head of clean clone of verdaccio repo (commit 7d71b060c4bdc64d023c978aa354c9cf00998161).

**Additional context**
Looking in the network tab of Dev Tools, the file is fetched. Just seems the dialog isn't opened for some reason. Double click the entry in the network tab and a new tab opens and I get the "Open With" dialog.

Tried Firefox on Fedora and Windows and also Edge (the pre-Chromium version) - no success. It doesn't appear in the browser's Downloads either.

I'm guessing it's not really a Verdaccio issue, but maybe this is the place to mention it first...

Thanks!

**Comment by sumanbh** [comment]
I took a stab at it [here](https://github.com/verdaccio/ui/pull/144/files). Let me know what you think.

**Comment by lukebelliott** [comment]
Works for me, thanks!
