### ISSUE TITLE
Upgrade React to v16.10.0

### ISSUE THREAD

**Issue by juanpicado** [verdaccio/ui#132]
**Describe the solution you'd like**

Upgrade to https://github.com/facebook/react/releases/tag/v16.10.0

**Comment by sergiohgz** [comment]
Let me verify changes and update this

**Comment by gzuzmark** [comment]
Hi, I'm Jesus Marquez. Is this an issue I can help with? Let me know if I can contribute to this one.

**Comment by sergiohgz** [comment]
All yours @gzuzmark :wink:
