### ISSUE TITLE
[Bug] Roboto font make 404 request in the WebUI

### ISSUE THREAD

**Issue by kopax** [verdaccio/ui#133]
![image](https://user-images.githubusercontent.com/1866564/65821036-99e8f700-e230-11e9-98ac-d6b0d74598ac.png)

Changing `staticfonts` instead of `static/fonts` would fix it.

Verdaccion version 4.2.2

**Comment by juanpicado** [comment]
Dupe 
https://github.com/verdaccio/ui/issues/128
