### ISSUE TITLE
Suggestion: Add the Storybook 

### ISSUE THREAD

**Issue by FilipMessa** [verdaccio/ui#140]
Will be nice for the developer experience to have some components playground.
I suggest using the Storybook because is easy to implement and customize.

Also with the storybook, you can integrate regressions test which is nice way how to test if components render properly. I don't like the jest component snapshot because on the end you end with big files full of lines of HTML markup. 
 
__links:__
Storybook: https://storybook.js.org/
Loki: https://loki.js.org (one of the options for visual regression tests)

**Comment by sergiohgz** [comment]
Storybook is a good option to create libraries, but in this case, is a final application, so the components should not go out of the scope of this plugin.
But thinking about the developer experience for the app, if we keep it out of the scope of the package build, is a real nice to have :smile:

**Comment by FilipMessa** [comment]
@sergiohgz
Sure It should not be part of the build, It should be just for a dev environment.

Storybook has also can be useful in other projects then UI library because when the app growing is nice to see all implemented component on one place without the need to run the whole application. It brings more advantage as you can easily check what components are ready to use, how looks their API, even if you need to create new is easy to start it develops in a storybook than in a real app.

So from a production perspective, it is nice to have, from the developer it can bring you some advantage but as a disadvantage, you must prepare stories for components.

**Comment by FilipMessa** [comment]
Cool, I'll take care of it over the weekend.

**Comment by juanpicado** [comment]
I have mixed filings about this, we should close it, I don't see a big benefit since we don't have a Design system that is reused anywhere else. We use material-ui and that's pretty much all.

**Comment by priscilawebdev** [comment]
I'm closing this for now
