### ISSUE TITLE
Lots of @ts-ignore in the codebase

### ISSUE THREAD

**Issue by antoinechalifour** [verdaccio/ui#151]
**Is your feature request related to a problem? Please describe.**
Right now there are of `@ts-ignore` : 
- in styles because the styled components are not typed correctly.
- in places where `window.XXX` is used
- in various other places :)

**Describe the solution you'd like**
- We could improve the code base by typing styled components :) https://emotion.sh/docs/typescript#passing-props
- We could add a declaration file for window properties

I can work on it and submit a PR

**Comment by antoinechalifour** [comment]
Currently working on it on this branch: https://github.com/antoinechalifour/ui/tree/fix-ts-ignore

**Comment by antoinechalifour** [comment]
I opened #153 which should fix some of them. This PR is mostly changes in typings so it does not impact the runtime :)

**Comment by juanpicado** [comment]
I am looking into it. :)
