### ISSUE TITLE
ForwardRef warnings

### ISSUE THREAD

**Issue by priscilawebdev** [verdaccio/ui#162]
**Current behaviour:**
As we are using a Material UI version above v3 and not all of our components in conjunction with Material-UI are not able to pass down the reference of parents to their children, we are  getting some warnings about ForwardRef. 

Example:

> Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

**Expected behaviour:**

We should wrap all Material UI components with ForwardRef, in order to fix this issue. You can read more about here: https://material-ui.com/guides/composition/#caveat-with-refs and here https://github.com/mui-org/material-ui/issues/14415

**Comment by juanpicado** [comment]
Great research.

**Comment by FilipMessa** [comment]
Do you need `forwardRef` for all components?
I didn't see that you use ref in all components from the `material-ui`  What is the reason for that?  Maybe I missed something.

BTW:  Does anybody know why I have few lint errors in my branch related to `./muiComponents` folder? (https://github.com/verdaccio/ui/pull/189)

Thanks, I am a beginner with typescript so any Idea will be welcome.

**Comment by juanpicado** [comment]
hi @FilipMessa, please double check you have all changes from master, if the issue persist I will take care of it.

**Comment by FilipMessa** [comment]
@juanpicado I used a rebase, so everything should be updated, but the problem still persists.
I have a plan to find some time and look at that today again but  I appreciate any help. 😉
thanks

**Comment by juanpicado** [comment]
I will take a look no worries, for now just use `--no-verify` on commit so do not block you if you wan to push changes.

**Comment by priscilawebdev** [comment]
I believe we can already close this one 👏🙂
