### ISSUE TITLE
Failing snapshots tests

### ISSUE THREAD

**Issue by FilipMessa** [verdaccio/ui#166]
**Describe the bug**
I downloaded a fresh master branch, installed the node modules with `yarn install`, run `yarn lint && yarn test` and then 23 snapshots test failed.

**To Reproduce**
1. clone repo
2. run `yarn install`
3. run `yarn lint && yarn test`

**Expected behavior**
I didn't change anything so tests should passed.

**Screenshots**
<img width="817" alt="Screen Shot 2019-10-07 at 10 21 55" src="https://user-images.githubusercontent.com/6354326/66296768-96b7d000-e8ee-11e9-9e86-90991b300785.png">

**Comment by FilipMessa** [comment]
@sergiohgz 🤔 
I don't have any changes in `yarn.lock` after-run `yarn install`, nevermind 
I tried to use the `yarn install --frozen-lockfile` but in the end, I get same results.

Environment:
```
macOS Mojave version: 10.14.6
node version: 12.11.1
yarn version: 1.17.3
```
The Jest version should be from the package.json.

**Comment by sergiohgz** [comment]
I don't have macOS to test it, but let me try in a CI running over macOS.

**Comment by sergiohgz** [comment]
CI using macOS has passed using [Node 10](https://github.com/verdaccio/ui/runs/250521111) and [Node 12](https://github.com/verdaccio/ui/runs/250521147). 
Take a look if you have something installed globally that breaks the tests. Also, run `jest --clearCache` to ensure that Jest cache is not corrupted

**Comment by FilipMessa** [comment]
I clear the cache as you suggested, and then I passed. 👍 
Thanks for help

**Comment by sergiohgz** [comment]
Perfect, Jest cache sometimes is a little bit weird
