### ISSUE TITLE
Page 404 miss some padding

### ISSUE THREAD

**Issue by juanpicado** [verdaccio/ui#194]
**Describe the bug**
<img width="591" alt="Verdaccio_-__verdaccio_active-directory" src="https://user-images.githubusercontent.com/558752/66712660-1e468880-eda0-11e9-9845-3f0f23ae63a1.png">

**Comment by jfamousket** [comment]
fixing this :)

**Comment by juanpicado** [comment]
Let me verify again, I noticed it in production mode.

**Comment by gdeusdara** [comment]
Maybe it depends on your browser! I'll check now

**Comment by gdeusdara** [comment]
I got this without touching a single of code
<img width="776" alt="Screen Shot 2019-10-14 at 22 58 59" src="https://user-images.githubusercontent.com/30842015/66794042-5819ab00-eed6-11e9-9492-1405379c4aaa.png">

**Comment by juanpicado** [comment]
From where did you take that screenshot ?

**Comment by jfamousket** [comment]
@juanpicado I took mine in chrome

**Comment by gdeusdara** [comment]
@juanpicado I took mine in chrome too, at master

**Comment by anikethsaha** [comment]
### Production ss

![image](https://user-images.githubusercontent.com/26347874/67572507-f23de680-f753-11e9-9895-fde32e31013f.png)

### Master

![image](https://user-images.githubusercontent.com/26347874/67572533-fe29a880-f753-11e9-9b81-4ad520270fe7.png)


Also
Why there are some difference between the production code and master ?
Like there are hover effects in the package detailed page for master : 

![image](https://user-images.githubusercontent.com/26347874/67572629-36c98200-f754-11e9-8ca3-37a8a2096168.png)


This is node there in the production code!

**Comment by DanielRuf** [comment]
This has nothing to do with Node itself.

I can also not reproduce it on `master` using `yarn dev`.
Closing as there are no clear steps to reproduce this.
