### ISSUE TITLE
Testing: Remove snapshots or limit them to small components rather pages

### ISSUE THREAD

**Issue by juanpicado** [verdaccio/ui#199]
**Is your feature request related to a problem? Please describe.**

Avoid

```
    const wrapper = shallow(<UpLinks />);
    expect(wrapper.html()).toMatchSnapshot();
```

It has 0 value with enzyme, is rather annoying to update them.

**Describe the solution you'd like**

- Replace by Testing library, find text or id.
- PR peer component (there are 39 matches in our source code)

**Comment by anikethsaha** [comment]
I think components using styling using `emotion` should not have snapshot testings!
Cause class name using emotion is dynamic and it will change on every run.

**Comment by juanpicado** [comment]
@anikethsaha agree with you, our configuration was not generating random classnames with emotion, so, snapshots should not be affected. If is the current situation, then is a bug.

**Comment by juanpicado** [comment]
Currently seems snapshots are generating random CSS name class, we need to figure out why.

**Comment by anikethsaha** [comment]
> Currently seems snapshots are generating random CSS name class, we need to figure out why.

if this problem persists, maybe migrating to emotion 10 may work as in v10, the styling is inline rather than class name.

**Comment by juanpicado** [comment]
That's the idea, #221  but @sergiohgz has some concerns about the complexity with Typescript.

**Comment by juanpicado** [comment]
This is want I want to avoid ... 

<img width="1630" alt="Screen Shot 2019-10-26 at 5 05 39 PM" src="https://user-images.githubusercontent.com/558752/67621718-e533fc80-f812-11e9-925f-8424702782fd.png">

**Comment by anikethsaha** [comment]
mm... I think this is related to material not particularly with emotion.

**Comment by anikethsaha** [comment]
Also, as using emotion, I saw `jest-emotion` is used to serialize the snapshots, it's being used in the jest config, but as per the docs `expect.addSnapshotSerializer(serializer)` needs to be added in the test files, Is it missed currently or handled in some other way?

**Comment by agar23** [comment]
@juanpicado need any help refactoring the other test's that are not using emotion? I would love to help help out on this front if needed.

**Comment by juanpicado** [comment]
Actually I would like to remove snapshots on pages, just limited to small components and those do not have dates.
