### ISSUE TITLE
[Minor-feat]: adding tarball download button in the packages lists

### ISSUE THREAD

**Issue by anikethsaha** [verdaccio/ui#217]
**Is your feature request related to a problem? Please describe.**
It would be a better experience for the developer to have the download button for the tarball in the packages list itself like that other two repo and bug buttons.

**Describe the solution you'd like**
To have the download button in the list item's right side along with the other buttons

**Describe alternatives you've considered**
NA

**Additional context**

![image](https://user-images.githubusercontent.com/26347874/67581121-1f46c500-f765-11e9-876c-a3d980ecc24c.png)

**Comment by juanpicado** [comment]
I like this 👍

**Comment by anikethsaha** [comment]
Thanks. I have started working on that. 
Just one thing though, Any idea why in `downloadhandler` when using in the `package` component is giving CORS error. I did add the `referrer` header as well.

**Comment by juanpicado** [comment]
There is no big magic behind the scenes, the domain is the same, we use webpack proxy ro route all request to the mock backend.

<img width="857" alt="Screen Shot 2019-10-26 at 12 41 25 PM" src="https://user-images.githubusercontent.com/558752/67618313-f880a100-f7ed-11e9-973c-90723deaabda.png">

```
  proxy: [
    {
      context: ['/-/verdaccio/**', '**/*.tgz'],
      target: 'http://localhost:8080',
    },
  ],
```

**Comment by anikethsaha** [comment]
@juanpicado I am getting this when using the exported `downloadHandler` from  `ActionBar`

![image](https://user-images.githubusercontent.com/26347874/67622066-ff320700-f833-11e9-9853-bccfe41b6d11.png)

**Comment by anikethsaha** [comment]
Here is the implementation 

https://github.com/anikethsaha/ui/blob/4bdf0168fe6687743e182559fddb38b1621fa3b9/src/components/Package/Package.tsx

**Comment by juanpicado** [comment]
🤔 why your code is fetching from npmjs?

**Comment by juanpicado** [comment]
The `dist.tarball` should point to `localhost`.
<img width="748" alt="Screen Shot 2019-10-26 at 6 11 53 PM" src="https://user-images.githubusercontent.com/558752/67622618-267cda00-f81c-11e9-91a4-48c46d57336d.png">

**Comment by anikethsaha** [comment]
Yeap.....the `dist.tarball` is having `npmjs` as link. 
this is what I am getting in the props for package component

![image](https://user-images.githubusercontent.com/26347874/67623128-92246e80-f83f-11e9-98d3-ed22747e4e20.png)

**Comment by anikethsaha** [comment]
@juanpicado any way to fix that wrong domain ?
The workaround I think is that to manually replace the domain name with localhost? What do you think

**Comment by juanpicado** [comment]
if you push your branch, I could take a look.

**Comment by anikethsaha** [comment]
https://github.com/anikethsaha/ui/blob/small-feat/tarball-btn-at-list/src/components/Package/Package.tsx

Here is the branch !!

**Comment by juanpicado** [comment]
Thanks @anikethsaha I'll check it out when I have some free time.
