### ISSUE TITLE
Faild to pass pre-commit hook

### ISSUE THREAD

**Issue by universeroc** [verdaccio/ui#236]
**Describe the bug**

pre-commit hook prevents my all code to commit to the repository event just one line e.g.
```
export const TIMEFORMAT = 'YYYY.MM.DD, HH:mm:ss';
```
**To Reproduce**

1. Go to 'src/utils/package.ts'
2. Modify the code
```
export const TIMEFORMAT = 'DD.MM.YYYY, HH:mm:ss';
```
3. git add -u && git commit -m "Update TIMEFORMAT"

**Expected behavior**

commit pass

**Screenshots**
![image](https://user-images.githubusercontent.com/3518853/68001350-ad0f3c80-fc9e-11e9-8413-deb86674c446.png)

**Docker || Kubernetes (please complete the following information):**
 - Docker Version [Docker version 19.03.4, build 9013bf5]

**Configuration File (cat ~/.config/verdaccio/config.yaml)**

**Environment information**
Windows 10 x64 Professional Edition 10.0.18362

**Comment by universeroc** [comment]
> Hi @universeroc,
> 
> did you already try `git add .secrets-baseline`?

.secrets-baseline already tracked in the git repo

**Comment by juanpicado** [comment]
Perhaps @lirantal can help here.

btw @universeroc . I noticed the commit format is wrong `git add -u && git commit -m "Update TIMEFORMAT"`

Read here how to do it https://github.com/verdaccio/verdaccio/blob/master/CONTRIBUTING.md#commit-guidelines

**Comment by universeroc** [comment]
> Perhaps @lirantal can help here.
> 
> btw @universeroc . I noticed the commit format is wrong `git add -u && git commit -m "Update TIMEFORMAT"`
> 
> Read here how to do it https://github.com/verdaccio/verdaccio/blob/master/CONTRIBUTING.md#commit-guidelines

Yeah, OK, got it! But the pre-commit hook can not pass even with right format, it's the core issue :(

**Comment by lirantal** [comment]
I'll take a look 👀

**Comment by lirantal** [comment]
I just did now a fresh clone of the repo followed by a yarn install, made the change as showing here and tried to commit, detect-secrets pass but the commit fails due to the commit conventions:

![image](https://user-images.githubusercontent.com/316371/68392427-72ac1080-0172-11ea-96ca-82d802a988ea.png)

if I use a proper commit message this works just fine though:

![image](https://user-images.githubusercontent.com/316371/68392492-8fe0df00-0172-11ea-907e-a79eef4e776c.png)

Any other tips on how to reconstruct the same issue you have @universeroc ?

**Comment by lirantal** [comment]
Actually the above is not accurate since I believe that on my local dev environment it just skipped that hook so I'm still looking into it.

**Comment by lirantal** [comment]
Took another look at it and I can't spot any issues, seems to work on my end. Maybe another dev can try making a small change, committing and seeing if this reproduces an error?

@universeroc can you track again your steps or try from a clean master version again and note everything that you do so I can try to follow-up on the same commands?

**Comment by universeroc** [comment]
> Took another look at it and I can't spot any issues, seems to work on my end. Maybe another dev can try making a small change, committing and seeing if this reproduces an error?
> 
> @universeroc can you track again your steps or try from a clean master version again and note everything that you do so I can try to follow-up on the same commands?

Yeah, great to get your reply, seems that you're working on Mac? I'll try it on my Mackbook and show the results

**Comment by lirantal** [comment]
I'm on a mac here. Thanks!

**Comment by universeroc** [comment]
> I'm on a mac here. Thanks!

Yeah, it proves that this bug only occurs on Windows

![image](https://user-images.githubusercontent.com/3518853/68468969-220ce400-0254-11ea-9ea0-ea2eec1c1681.png)

**Comment by lirantal** [comment]
Just a sec though, because that error now is related to the linting of commit messages, not the secrets. Try to commit with a proper message like `git commit -m "feat: update readme"`

**Comment by universeroc** [comment]
> Just a sec though, because that error now is related to the linting of commit messages, not the secrets. Try to commit with a proper message like `git commit -m "feat: update readme"`

Sorry to tell you, it's the not the primary source of this error. I've tried to use a good commit message to commit, but the console error message is all the same with previous.

![image](https://user-images.githubusercontent.com/3518853/68555900-e4ce6f00-046a-11ea-88f9-88035e241924.png)

**Comment by DanielRuf** [comment]
Hm, this is weird. Is this a bug with Husky or something else?

**Comment by lirantal** [comment]
what is very odd here is that `detect-secrets-launcher` tries to execute with some files I assume but fails, however which file is provided to it? because it looks like both changed files are not staged for commits, so they shouldn't be provided to it. Perhaps that's the issue. What happens if you add them, and then commit?

**Comment by juanpicado** [comment]
Should we keep this open?

**Comment by lirantal** [comment]
@universeroc are you still having a problem there? and is it reproducible?

**Comment by universeroc** [comment]
> @universeroc are you still having a problem there? and is it reproducible?

Yeah, it is also reproducible. To your lastest reply https://github.com/verdaccio/ui/issues/236#issuecomment-555234832

I cannot add them, I've tried in the very beginning of this issue
