### ISSUE TITLE
Suggestion: Prism Support

### ISSUE THREAD

**Issue by dylanb124** [verdaccio/ui#3]
I believe it would be beneficial to add support for [Prism.js](http://prismjs.com/). Currently, there is not any markdown syntax coloring in the web ui.

I attempted adding the support in manually via inserting the css and js in `static/index.html`, but was unsuccessful as the files were not exported to the server.

**Comment by juanpicado** [comment]
This has been open for long time, I'll close it since we don't have interest on develop it, if someone wants to do it, go ahead opening a  PR.
