### ISSUE TITLE
Suggestion: Perhaps support additional protocols in the package repository section

### ISSUE THREAD

**Issue by a666** [verdaccio/ui#301]
Right now only the following are protocols are classified as URL and displayed by the web interface:

https://github.com/verdaccio/ui/blob/b56e43846bc1492d15cd5c4e49857e4f1bfa4c1c/src/utils/url.ts#L7

Perhaps it would be useful for other protocols to be supported, specially all protocols that package.json supports. These being git, git+ssh, git+http, git+https and git+file.

Is there a particular reason for them to not be, specially because I think a fix for this would be very straightforward?

Edit: 
I've just checked the tests. https://github.com/verdaccio/ui/blob/5d300cd9be530197bc0eb4e413ad04bddc9cec68/src/components/Repository/Repository.test.tsx#L63

Is really this behavior wanted?

**Comment by juanpicado** [comment]
Hi,

I understand your point of view, but the protocols 

```
git+ssh, git+http, git+https and git+file.
```

won’t be useful in the UI, user won’t be able to download a file and so own. Anyway, I would prefer encourage users to use http protocols which is the one we use to fetch packages.

**Comment by juanpicado** [comment]
Wait a minute ... you refer to repositories .... not tarballs ...

**Comment by a666** [comment]
![image](https://user-images.githubusercontent.com/19142162/69383480-55e9ff80-0c7f-11ea-9b8c-a4a19d0b2816.png)

That's right. In our particular use case copying the repository, the git+ssh url, to clipboard would be very useful for our private packages.

**Comment by juanpicado** [comment]
hi @a666 I think make sense what your purpose, but keep on mind the same components is used in other places. For me is +1 your enhancement.

**Comment by a666** [comment]
Want me to do a PR?

**Comment by DanielRuf** [comment]
> Want me to do a PR? The change is pretty small I think.

This would be very great =)
