### ISSUE TITLE
isUserLoggedIn prop is not being used

### ISSUE THREAD

**Issue by juanpicado** [verdaccio/ui#309]
**Describe the bug**

`isUserLoggedIn` is being set on `AppRoute` but not being used within `Home`.

```
import React from 'react';

import { PackageList } from '../../components/PackageList';
import { PackageInterface } from '../../components/Package/Package';

interface Props {
  isUserLoggedIn: boolean;
  packages: PackageInterface[];
}

const Home: React.FC<Props> = ({ packages }) => (
  <div className="container content">
    <PackageList packages={packages} />
  </div>
);

export default Home;
```

**Comment by DanielRuf** [comment]
It was last used in https://github.com/verdaccio/verdaccio/commit/9d265996f9e68067e5c0fb10f0ab25129235ad6f#diff-419acda00d07b9e5ef8084cb09d1d057L65

So I guess it can be safely removed now?

**Comment by DanielRuf** [comment]
Unfortunately it seems these were many commits and they were squashed (we should never squash, especially when the PR title does not fit).

On the right side in the new Home page it is missing. So not sure why this was removed.

**Comment by DanielRuf** [comment]
We should probably use SonarCloud to find more such code smells.

**Comment by priscilawebdev** [comment]
@juanpicado good catch!

**Comment by tmkn** [comment]
> We should probably use SonarCloud to find more such code smells.

For what it's worth here's a scan of the project I did in December(?) with default settings, if anyone wants to have a quick look what it looks like.
https://sonarcloud.io/dashboard?id=tmkn_ui

Thanks for reminding me that I set this up, I actually wanted to propose SonarCloud 😅 

The Pull Request integration is also pretty nice.

**Comment by DanielRuf** [comment]
I might have to do some new scans
https://sonarcloud.io/dashboard?id=DanielRuf_ui
https://sonarcloud.io/dashboard?id=DanielRuf_verdaccio

I have created a PR, let's discuss this there: https://github.com/verdaccio/ui/pull/408

**Comment by coolsp** [comment]
Don't remove `isUserLoggedIn` from `Home` yet... I found a good use for it to trigger reloading the packages-list when a user logs-in/out.  About to create a bug report + PR.

**Comment by juanpicado** [comment]
I guess we can close this right ?

**Comment by coolsp** [comment]
Yes, thanks @juanpicado !
