### ISSUE TITLE
Info dialog is broken, registry url is incorrect

### ISSUE THREAD

**Issue by juanpicado** [verdaccio/ui#310]
**Describe the bug**

Detail explanation here https://github.com/verdaccio/ui/pull/300#issuecomment-557917138

![Screen Shot 2019-11-24 at 7 52 52 PM](https://user-images.githubusercontent.com/558752/69499685-03b21400-0ef5-11ea-9a50-97169c1f17e8.png)

**To Reproduce**
1. Run `yarn dev`
2. Open info dialog

**Expected behavior**

The registry url is correct.

**Screenshots**

**Docker || Kubernetes (please complete the following information):**
 - Docker verdaccio tag: [e.g. verdaccio:beta]
 - Docker commands [e.g. docker pull ...]
 - Docker Version [e.g. v18.05.0-ce-rc1]

**Configuration File (cat ~/.config/verdaccio/config.yaml)** 

**Debugging output**
 - `$ NODE_DEBUG=request verdaccio` display request calls (verdaccio <--> uplinks)
 - `$ DEBUG=express:* verdaccio` enable extreme verdaccio debug mode (verdaccio api)
 - `$ npm -ddd` prints:
 - `$ npm config get registry` prints:

**Additional context**

**Comment by anikethsaha** [comment]
Keeping the url in top-down props may be helpful here

**Comment by priscilawebdev** [comment]
I am closing this issue, since it seems to be fine now :-) great job! 
![image](https://user-images.githubusercontent.com/29228205/71695486-8fe80e80-2db2-11ea-9003-9a44fdfc34fc.png)

**Comment by priscilawebdev** [comment]
I am closing this issue, since it seems to be fine now :-) great job! 
![image](https://user-images.githubusercontent.com/29228205/71695486-8fe80e80-2db2-11ea-9003-9a44fdfc34fc.png)
