### ISSUE TITLE
Display funding on UI

### ISSUE THREAD

**Issue by juanpicado** [verdaccio/ui#361]
**Is your feature request related to a problem? Please describe.**

Currently the metadata has a new field, funding, supported by the command `npm fund` and I want to display it in the UI.

```
 "10.0.5": {
            "name": "preact", 
            "amdName": "preact", 
            "version": "10.0.5",          
            "license": "MIT", 
            "funding": {
                "type": "opencollective", 
                "url": "https://opencollective.com/preact"
            }, 
```

Context: https://github.com/npm/rfcs/pull/54

This also requires, update https://github.com/verdaccio/monorepo/tree/master/core/types

**Describe the solution you'd like**

1. Just below the package name
2. Add as a button ( but it has less visibility)
3. Below installation panel
4. Propose something else 🤔 

![Verdaccio_-__verdaccio_babel-preset](https://user-images.githubusercontent.com/558752/70687482-9e5d7180-1caf-11ea-8c5a-3d0ab6ddefe0.png)

**Additional context**

I want Verdaccio contribute to funding packages across al interfaces.
**On click a new tab must be open**

**Comment by priscilawebdev** [comment]
I really like the idea!! Can I take it over?  @verdaccio/core-team  😀

**Comment by DanielRuf** [comment]
Great idea.
This would be cool @priscilawebdev =)

**Comment by hugoazevedosoares** [comment]
Nice one. I think the number 2 proposal will look better, but on proposal 3 it may be more visible.

**Comment by DanielRuf** [comment]
I think proposal 3 is best (clearly shown as external link).

Wasn't there also a demo of npmjs with the funding links?

**Comment by anikethsaha** [comment]
+1 for this.
Lets go with 3rd with a wide button like npm is having it now.

**Comment by juanpicado** [comment]
Thanks guys I think proposal 3 would be.

**Comment by priscilawebdev** [comment]
I still need to update the funding use cases, but as the funds button is already there, I think I can close this issue ☺️

**Comment by juanpicado** [comment]
The PR #375  only add a button with no behavior as far I can see, so I reopen this until is fully working.

ref https://github.com/verdaccio/ui/pull/375

**Comment by DanielRuf** [comment]
Isn't it already working there with the sryled link? https://github.com/verdaccio/ui/pull/375/files (I see more changes again than just the addition of the button, we should do refactorings in separate PRs).

What is currently missing?

**Comment by juanpicado** [comment]
see https://github.com/verdaccio/ui/issues/410 , I released yesterday and I did no know the #375 was merge and now we have a bug. I will take care of it.

**Comment by juanpicado** [comment]
> What is currently missing?

The button does not do anything, check https://github.com/verdaccio/ui/blob/master/src/components/DetailSidebar/DetailSidebarFundButton.tsx#L30

**Comment by DanielRuf** [comment]
Hm, I see no approved code review. We should probably require / enforce this here too. And at least one or two approved reviews should be done.

At least I see no green code reviews on my smartphone =)

**Comment by juanpicado** [comment]
I will enable "Include Administrators", since all core team is admin now, we should behave as normal contributors, of course, this also imply that we @verdaccio/core-team  should not let others block for so long, otherwise might be frustrating. But, this will avoid we merge incomplete stuff again.
