### ISSUE TITLE
background for icons is not transparent

### ISSUE THREAD

**Issue by juanpicado** [verdaccio/ui#371]
**Describe the bug**

Some shadows surround the icons.

![Screen Shot 2019-12-16 at 9 04 49 PM](https://user-images.githubusercontent.com/558752/70939056-c0f0e100-2047-11ea-9677-a6df726cdf67.png)

**To Reproduce**
1. Just go to any detail page

**Expected behavior**

White or transparent brackground

**Comment by juanpicado** [comment]
Also ...

![Screen Shot 2019-12-16 at 9 10 58 PM](https://user-images.githubusercontent.com/558752/70939448-93f0fe00-2048-11ea-939c-d03118eda5e3.png)

**Comment by DanielRuf** [comment]
How should it look like? No background at all?
