### ISSUE TITLE
Background and container is duplicated

### ISSUE THREAD

**Issue by juanpicado** [verdaccio/ui#373]
**Describe the bug**
There is a double container which add extra 15px padding to the whole container. Furthermore the background is not white `#FFFFF` anymore.

**To Reproduce**

Compare `yarn dev` `http://localhost:4872/-/web/detail/verdaccio` vs `https://registry.verdaccio.org/-/web/detail/verdaccio`

**Expected behavior**

Remove the extra-container

**Screenshots**
Before

<img width="1380" alt="Screen Shot 2019-12-16 at 9 13 50 PM" src="https://user-images.githubusercontent.com/558752/70939687-0cf05580-2049-11ea-9135-bfe4d686c579.png">

now

<img width="1421" alt="Screen Shot 2019-12-16 at 9 14 02 PM" src="https://user-images.githubusercontent.com/558752/70939697-11b50980-2049-11ea-84f4-ff07c99e1539.png">

**Comment by DanielRuf** [comment]
Old:

<img width="544" alt="Bildschirmfoto 2019-12-25 um 14 37 45" src="https://user-images.githubusercontent.com/827205/71446497-4fd6bb00-2724-11ea-9977-a1329745bb85.png">

Current:
<img width="369" alt="Bildschirmfoto 2019-12-25 um 14 39 20" src="https://user-images.githubusercontent.com/827205/71446513-6f6de380-2724-11ea-8690-70626f7e566d.png">


It seems the `MuiBox-root` is new.

**Comment by DanielRuf** [comment]
Was introduced by https://github.com/verdaccio/ui/commit/0d9232a92cbe3d507f43c2ae86278a63ac23996d#diff-2d39dbde05630bdfe781f3a465e7857bL46 and https://github.com/verdaccio/ui/commit/0d9232a92cbe3d507f43c2ae86278a63ac23996d#diff-2d39dbde05630bdfe781f3a465e7857bL159

We should stop squashing commits, cc @priscilawebdev - this makes it hard to understand why it was changed there as this is not related to the actual refactoring.

**Comment by DanielRuf** [comment]
It seems `<Content>` was replaced but we still have the styles in https://github.com/verdaccio/ui/blob/111f0c50e5053202ca55fe4f3f28dd30e4932240/src/components/Layout/Layout.tsx#L6 but we forgot to copy the `backgroundColor`property.
