### ISSUE TITLE
Header icon is displaced in header

### ISSUE THREAD

**Issue by juanpicado** [verdaccio/ui#374]
**Describe the bug**

The icon is displaced and not centered anymore.

![Kapture 2019-12-16 at 21 20 16](https://user-images.githubusercontent.com/558752/70940138-fac2e700-2049-11ea-8c5c-6a58695d3701.gif)

**To Reproduce**

Just compare local master 

`http://localhost:4872/-/web/detail/jquery`
vs
`https://registry.verdaccio.org/-/web/detail/jquery`

**Expected behavior**

Icon should be center and match with the `v4.3.4`

**Comment by DanielRuf** [comment]
Can we do a quick `git bisect`?

**Comment by juanpicado** [comment]
There has been a lot of refactoring lately, it would be hard to find.

**Comment by DanielRuf** [comment]
I'' check that.

**Comment by DanielRuf** [comment]
I'll check that.

**Comment by DanielRuf** [comment]
bad: v0.3.6

Interesting, express seems to have removed some release. 4.18.0 was / is referenced in the lockfile but does not exist (anymore).

express/-/express-4.18.0.tgz

**Comment by juanpicado** [comment]
We had that issue before and we fixed it (removing the cached version) ... I don't see it anymore.  Where are you seeing that?

Actually `express/-/express-4.18.0.tgz` was published early this year and then removed (it seems inside of this 72h window) ... but we cached it .. funny thing is from our registry all was fine but was failing in the CI due in that time we were fetching from npmjs. Interesting discovery. cc: @sergiohgz

**Comment by DanielRuf** [comment]
It's in the yarn.lock of v0.3.2 and you fixed it in a PR. See https://github.com/verdaccio/verdaccio/pull/1490

**Comment by juanpicado** [comment]
Yes, also we had to remove it manually from our registry.

**Comment by DanielRuf** [comment]
http://localhost:4872/

<img width="427" alt="Bildschirmfoto 2019-12-25 um 21 45 21" src="https://user-images.githubusercontent.com/827205/71450307-e07ebc80-275f-11ea-9b76-739399558c2c.png">

http://localhost:8080/

<img width="841" alt="Bildschirmfoto 2019-12-25 um 21 45 54" src="https://user-images.githubusercontent.com/827205/71450309-f12f3280-275f-11ea-8c8b-e49f23f746ff.png">

The good ol' `font-size: 0` trick.

**Comment by DanielRuf** [comment]
<img width="738" alt="Bildschirmfoto 2019-12-25 um 21 56 43" src="https://user-images.githubusercontent.com/827205/71450403-7ff07f00-2761-11ea-9252-9ecb108b578e.png">
<img width="750" alt="Bildschirmfoto 2019-12-25 um 21 57 01" src="https://user-images.githubusercontent.com/827205/71450404-7ff07f00-2761-11ea-869b-d81bf51313b1.png">
