### ISSUE TITLE
get font error

### ISSUE THREAD

**Issue by pianfeng240** [verdaccio/ui#395]
**Describe the bug**
log show 404 error : 
req: 'GET /-/staticfonts/roboto-latin-400.woff', error: File not found

1. version: 4.4.0, run by docker-compose
2. after service start, refresh home page

**Expected behavior**
font exist

**Screenshots**
![image](https://user-images.githubusercontent.com/11719252/70985924-ec330900-20f7-11ea-8c1c-ba18eba05d04.png)

**Comment by DanielRuf** [comment]
It seems it was changed in https://github.com/verdaccio/ui/commit/09fe1db8508aff5bad702425a874bfc805dfed9e

https://github.com/verdaccio/ui/blame/master/tools/webpack.config.js#L71

This was fixed by https://github.com/verdaccio/ui/commit/f61913c2d351d8e316017e739ee47f5d739683ba before this.

**Comment by DanielRuf** [comment]
Let's fix the publicPath once and for all (missing trailing slash):
https://github.com/verdaccio/ui/blob/09fe1db8508aff5bad702425a874bfc805dfed9e/tools/webpack.config.js#L11
