### ISSUE TITLE
Getting warnings regarding props in context on build

### ISSUE THREAD

**Issue by DanielRuf** [verdaccio/ui#397]
**Describe the bug**
When I do a `yarn build`on current `master`branch the webpack build gives me the following warnings:

```shell
WARNING in ./src/pages/Version/index.ts 5:0-134
"export 'DetailContextProps' was not found in './context'
 @ ./src/App/AppRoute.tsx
 @ ./src/App/App.tsx
 @ ./src/App/index.ts
 @ ./src/index.tsx
 @ multi babel-polyfill whatwg-fetch ./src/index.tsx

WARNING in ./src/muiComponents/Text/index.ts 5:0-44
"export 'TextProps' was not found in './Text'
 @ ./src/components/Link/Link.tsx
 @ ./src/components/Link/index.ts
 @ ./src/components/Header/styles.ts
 @ ./src/components/Header/Header.tsx
 @ ./src/components/Header/index.ts
 @ ./src/App/App.tsx
 @ ./src/App/index.ts
 @ ./src/index.tsx
 @ multi babel-polyfill whatwg-fetch ./src/index.tsx

WARNING in ./src/pages/Version/index.ts 5:0-134
"export 'VersionPageConsumerProps' was not found in './context'
 @ ./src/App/AppRoute.tsx
 @ ./src/App/App.tsx
 @ ./src/App/index.ts
 @ ./src/index.tsx
 @ multi babel-polyfill whatwg-fetch ./src/index.tsx

WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets: 
  vendors.73c265ce133439987c63.js (578 KiB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  main (694 KiB)
      manifest.73c265ce133439987c63.js
      0.style.b3d2b69b057068c678ca.css
      vendors.73c265ce133439987c63.js
      main.73c265ce133439987c63.js
```

**To Reproduce**
1. Run `yarn build`

**Expected behavior**
There should not be any warnings.

**Comment by w-ko** [comment]
Is this possibly related to https://github.com/webpack/webpack/issues/7378#issuecomment-492641148 ?

When I split up the interfaces and types into separate files at least part of the warnings disappear:

**Affecting the first two warnings**:
![image](https://user-images.githubusercontent.com/59027568/71491336-68cc9280-2830-11ea-83e6-14fe8e435a69.png)
![image](https://user-images.githubusercontent.com/59027568/71491348-84d03400-2830-11ea-8b9b-1d4bd4aa6f59.png)

Export to separate file:
![image](https://user-images.githubusercontent.com/59027568/71491234-cf9d7c00-282f-11ea-9370-5e2092dfdaa8.png)
![image](https://user-images.githubusercontent.com/59027568/71491223-b8f72500-282f-11ea-8537-3fec45337652.png)
Exported Interfaces removed from index file
![image](https://user-images.githubusercontent.com/59027568/71491255-ee037780-282f-11ea-97e4-8cfbdca5a57d.png)

**Analogous for the text warning**
![image](https://user-images.githubusercontent.com/59027568/71491464-1770d300-2831-11ea-9ac9-352e864f3102.png)

Here again as separate file:
![image](https://user-images.githubusercontent.com/59027568/71491491-471fdb00-2831-11ea-9a69-4348577d34b8.png)

Afterwards only the following warning remains:
![image](https://user-images.githubusercontent.com/59027568/71491522-7cc4c400-2831-11ea-8cd2-fa4cb65fc61c.png)

I am not sure about this one though... :-(

**Comment by DanielRuf** [comment]
As others already stated in the webpack issue this is probably an issue with the TypeScript compiler (and a feature probably). So yes, we might try the linked solution.

**Comment by priscilawebdev** [comment]
Honestly, I don't like the current solution very much :/ maybe there is another way
