### ISSUE TITLE
Add script to update snapshots

### ISSUE THREAD

**Issue by DanielRuf** [verdaccio/ui#401]
**Is your feature request related to a problem? Please describe.**
As a developer I want to update snapshots when needed.

**Describe the solution you'd like**
As @juanpicado proposed:
> At jest you need to add an argument -u. Perhaps worth to add a new script
> 
> "test:snapshopts": "npm run test -- -u",
> 
> to facilitate this process while the other ticket is being fixed.

**Comment by agar23** [comment]
is #416 all we need?

**Comment by sergiohgz** [comment]
I don't think we need to create an scripts to update snapshots, as it's not a task that should bun run frequently.
If we still want a script, I think `test:snapshot` it's not semantically correct, it tells me more to run snapshot tests than update them.

**Comment by agar23** [comment]
If we do decide to merge this, I updated the script to `test:update-snapshot`
