### ISSUE TITLE
Fund button is not working

### ISSUE THREAD

**Issue by juanpicado** [verdaccio/ui#410]
**Describe the bug**

On click the button nothing happens. #361 

**To Reproduce**
1. Install the last release verdaccio `v4.4.1`
2. Load `http://localhost:4873/-/web/detail/verdaccio`
3. Click on button

**Expected behavior**
should open the targeted url

**Screenshots**

![Screen Shot 2020-01-04 at 9 47 08 AM](https://user-images.githubusercontent.com/558752/71763010-3299ad80-2ed7-11ea-99f7-ddb7e8b0b336.png)

**Comment by DanielRuf** [comment]
I think you mean `4.4.1`, I have changed it ;-)

**Comment by DanielRuf** [comment]
So we should provide functional tests with new features or test it manually and not just do a code review =)

Where can we put the needed tests?

**Comment by juanpicado** [comment]
Yes, we should. The test are in the same folder as far I can see.  Are you taking care of it? or  me? 🙃 ... I was doing it already ...

**Comment by DanielRuf** [comment]
You can work on it. I would be happy to review it then =)

**Comment by juanpicado** [comment]
> The button does not do anything, check https://github.com/verdaccio/ui/blob/master/src/components/DetailSidebar/DetailSidebarFundButton.tsx#L30

I did not notice the `StyledLink` is actually an `<a/>`, so, still a bug but is not working because the `preventDefault` actually block the default event, which bubble up the click event.
