### ISSUE TITLE
Names are displayed with uppercase 

### ISSUE THREAD

**Issue by juanpicado** [verdaccio/ui#428]
**Describe the bug**

Names are displayed with uppercase 

**To Reproduce**
1. Go to https://registry.verdaccio.org/-/web/detail/@verdaccio/active-directory

**Expected behavior**

Packages name should not be uppercased

**Screenshots**
![Screen Shot 2020-02-01 at 5 42 53 PM](https://user-images.githubusercontent.com/558752/73595547-5bcf4d00-451a-11ea-969c-526a7cdee881.png)

**Comment by DanielRuf** [comment]
I see the following in Firefox:
<img width="787" alt="Bildschirmfoto 2020-02-01 um 22 15 48" src="https://user-images.githubusercontent.com/827205/73599135-6d2b5000-4540-11ea-9409-38969ee5f8e0.png">

**Comment by DanielRuf** [comment]
Weird, now it is different (Firefox)?

<img width="373" alt="Bildschirmfoto 2020-02-01 um 22 16 47" src="https://user-images.githubusercontent.com/827205/73599148-9350f000-4540-11ea-8fc1-3af96a74027b.png">

**Comment by DanielRuf** [comment]
Found it, working on it.

<img width="714" alt="Bildschirmfoto 2020-02-01 um 22 17 30" src="https://user-images.githubusercontent.com/827205/73599154-aa8fdd80-4540-11ea-9820-592126d855bd.png">
