### ISSUE TITLE
Add a new flag

### ISSUE THREAD

**Issue by juanpicado** [verdaccio/ui#433]
**Is your feature request related to a problem? Please describe.**

![Screen Shot 2020-02-05 at 7 20 10 PM](https://user-images.githubusercontent.com/558752/73870640-bb946380-484c-11ea-9ec3-437b6de80693.png)

I live in Germany, big part of the core teams lives and contribute from Germany, I would vote to add it to the list, What do you think?

**Comment by anikethsaha** [comment]
Its hard to track every contributor's country but its good to have. I would say add this to the main site as well

**Comment by juanpicado** [comment]
The original idea of the flags was mostly for the people which start the UI, like “made in xx” seal, just some innocent brand which ended up being part of the image in the UI, I wonder how many people actually expand the flags.
