### ISSUE TITLE
"Download tarball" HTTP 401 (Unauthorized) affecting 4.5.1

### ISSUE THREAD

**Issue by reviewher** [verdaccio/ui#444]
https://github.com/verdaccio/ui/issues/75 appears to have been closed, but the issue has reappeared.  The verdaccio log shows unauthenticated GET requests for the tarballs.

**Comment by juanpicado** [comment]
Please fill this template before report and issue, that makes more easy to understand to track source of the problem.
https://raw.githubusercontent.com/verdaccio/ui/master/.github/issue_template.md

**Comment by reviewher** [comment]
To be sure, it is the exact problem reported in the previously closed issue, except it has reappeared in the latest version

**Comment by hdmr14** [comment]
may related to https://github.com/verdaccio/verdaccio/issues/1508 ?
issue still exist on 4.6.1

**Comment by juanpicado** [comment]
Thanks @hdmr14 , all please check my comment at https://github.com/verdaccio/verdaccio/issues/1508 

I need your help or we will never solve the issue.

**Comment by juanpicado** [comment]
closed by https://github.com/verdaccio/verdaccio/issues/1508
