### ISSUE TITLE
wrong css background color

### ISSUE THREAD

**Issue by hathub** [verdaccio/ui#445]
Hi all,
I've just updated my verdaccio from version 4.2.2 to 4.5.1 and I've noticed a little UI problem on my homepage:
![Annotazione 2020-03-19 175925](https://user-images.githubusercontent.com/4267083/77094289-90d12980-6a0c-11ea-9dd8-b38290e3582a.jpg)

Light grey border appear when I start to scroll down any page. Why background color of body is set to `#fafafa` and not to `#ffffff` ?

Thanks in advance!

**Comment by hathub** [comment]
I've just installed verdaccio 4.8.1 and this problem seems fixed.

Thanks

**Comment by priscilawebdev** [comment]
Oh I am glad that the problem is already fixed. Thank you for letting us know @hathub  :)
