### ISSUE TITLE
The header style is broken in IE11

### ISSUE THREAD

**Issue by juanpicado** [verdaccio/ui#447]
**Describe the bug**
The header is broken in IE11

**To Reproduce**
1. Go to home

**Expected behavior**

The header must look like in other browsers

**Screenshots**
![Screen Shot 2020-03-29 at 12 45 10 PM](https://user-images.githubusercontent.com/558752/77847156-34fc6280-71bb-11ea-9028-797706ae93bf.png)

**Comment by anikethsaha** [comment]
I think this kind of issue should be solved by `autoprefixer` in `prod` webpack config.
something like this in `webpack.prod.config.babel.js`

```js
   new OptimizeCSSAssetsPlugin({
        cssProcessor: css => postcss([require('autoprefixer'), require('cssnano')]).process(css),
      }),
```

I tried this, faced some issue like not able to handle `tsx` files (not related to this solution..)
but I couldnt push my code to my fork

getting this

![image](https://user-images.githubusercontent.com/26347874/77850414-0056ce00-71f0-11ea-8a72-d66adbe62710.png)

**Comment by juanpicado** [comment]
Try again :)

**Comment by juanpicado** [comment]
I'll migrate to webpack 5 and remove IE 11 support in the next release.
