### ISSUE TITLE
Contributor section is displayed if it comes empty 

### ISSUE THREAD

**Issue by juanpicado** [verdaccio/ui#458]
**Describe the bug**

<img width="239" alt="Screen Shot 2020-04-08 at 10 44 55 PM" src="https://user-images.githubusercontent.com/558752/78831881-aec9f280-79ea-11ea-9b51-c268afc2ecb6.png">
<img width="410" alt="Screen Shot 2020-04-08 at 10 44 50 PM" src="https://user-images.githubusercontent.com/558752/78831885-af628900-79ea-11ea-932a-88ea4b7bd45e.png">

**To Reproduce**
1. Go to https://registry.verdaccio.org/-/web/detail/verdaccio

**Expected behavior**

It should hide the section

**Comment by priscilawebdev** [comment]
done.
