### ISSUE TITLE
Add prefers-color-scheme for theme preference

### ISSUE THREAD

**Issue by himanshumehta1114** [verdaccio/ui#464]
**Is your feature request related to a problem? Please describe.**
Right now verdaccio dark theme can be set by admin by default or the user can enable it manually but it would be better if we could add [prefer-colors-scheme](https://master--material-ui.netlify.app/customization/palette/#user-preference) and let the system decide which theme should be preferred. and also keep the currently functionality i.e user can also toggle the theme manually

**Describe the solution you'd like**
We can add [prefer-colors-scheme](https://master--material-ui.netlify.app/customization/palette/#user-preference) media query as our priority and user can then toggle the theme as well.

**Additional context**
https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme
https://master--material-ui.netlify.app/customization/palette/#user-preference

I would love to work on this issue and thanks for giving dark theme. Amazing work 👏

**Comment by juanpicado** [comment]
The support still quite low, but looks like a nice feature.
https://caniuse.com/#feat=prefers-color-scheme

I wonder how this might work with Material-UI, I guess @priscilawebdev might have an opinion here.

**Comment by himanshumehta1114** [comment]
@priscilawebdev @juanpicado just came to ring the bell 😄 . Any updates here?

**Comment by juanpicado** [comment]
Nothing new. I don't expect updates here for a while.  If anyone want experiment in this area go ahead 👍.

**Comment by DanielRuf** [comment]
Definitely a good idea to add this.

**Comment by juanpicado** [comment]
Tagged properly for the :) next month event

**Comment by priscilawebdev** [comment]
oh yes.. Hacktoberfest is coming and yess this is a very good idea 😀👏

**Comment by priscilawebdev** [comment]
@himanshumehta1114  please do you still plan to work on this issue? otherwise can I please take it over?

**Comment by himanshumehta1114** [comment]
@priscilawebdev I do plan to work on this one. Will raise the PR soon.

**Comment by himanshumehta1114** [comment]
`yarn lint` gives me these warnings on **master** 👉 

<img width="1678" alt="Screenshot 2020-10-09 at 12 38 07 AM" src="https://user-images.githubusercontent.com/25463496/95502695-d6187100-09c7-11eb-95a3-11974aa29d17.png">

**Comment by priscilawebdev** [comment]
done
