### ISSUE TITLE
Date format uses a different locale

### ISSUE THREAD

**Issue by juanpicado** [verdaccio/ui#465]
**Describe the bug**
The date does not use the locale selected for translation, then looks different.

**Expected behavior**

The date should be formatted according the locale selected.

**Screenshots**

<img width="763" alt="Screen Shot 2020-05-01 at 12 57 24 PM" src="https://user-images.githubusercontent.com/558752/80801047-79f52980-8bab-11ea-9a84-3fea10e2eb6a.png">

**Comment by hdmr14** [comment]
It caused by day.js locale not updated when locale selected.
I'll try to solve this.

**Comment by hdmr14** [comment]
I'll take times longer than I thought...
I'm not familiar with React but I'll do my best until anyone familiar with React want to contribute this comes.
I don't blocking your contribute!

**Comment by hdmr14** [comment]
I can confirm that this issue fixed by b59840d at #472, Thanks for!
Sorry for I couldn't help to this...😭
