### ISSUE TITLE
Registry Info window has wrong header style in Dark mode

### ISSUE THREAD

**Issue by VentyCZ** [verdaccio/ui#478]
**Describe the bug**
In Dark mode, header for Registry Info window has wrong styling (white background with white text).

**To Reproduce**
1. Switch to Dark mode using sun icon in the header
2. Click info icon in the header
3. See error

**Expected behavior**
The header should have similar styling to the Login window

**Screenshots**
![Screenshot](https://i.gyazo.com/d7bd42fb2a5ffa4b21e38867dc44a2d6.png)
https://gyazo.com/d7bd42fb2a5ffa4b21e38867dc44a2d6

**Comment by juanpicado** [comment]
hi @VentyCZ thanks for reporting, please describe environment, specially browser :)

**Comment by VentyCZ** [comment]
@juanpicado Verdaccio 4.6.2 installed through yarn.
Tested on latest Chrome (v81) on both Linux and Windows 10.
Can send registry url privately, so you can check it.

**Comment by VentyCZ** [comment]
After some investigation (still quite new to the overall project structure) I found out, that the issue is affecting more than this component.
The issue is that color has a static value of 'white' while the 'primary' (background) color used for dark theme is white (#fff).

![image](https://user-images.githubusercontent.com/3247664/84565803-2e1dce80-ad6c-11ea-8bf6-d81f5154dcb5.png)
