### ISSUE TITLE
Evaluate  https://github.com/bvaughn/react-window to render the package list

### ISSUE THREAD

**Issue by priscilawebdev** [verdaccio/ui#491]

**Comment by juanpicado** [comment]
It seems outdated, last release was 1.5 years ago

**Comment by priscilawebdev** [comment]
Yes, it was in 2018, but still the project seems to be one of the best when it comes to rendering large lists... there is also the react-virtualized created by the same person...it looks active... but the problem is: it is large... it comes with a lot of features that we don't need...

**Comment by juanpicado** [comment]
Yeah, agree `react-virtualized` is heavy, but still seems unmaintained.

What about the other options the README suggest  https://github.com/bvaughn/react-window#related-libraries?

**Comment by priscilawebdev** [comment]
@juanpicado I will evaluate them 😉

**Comment by juanpicado** [comment]
We have already `react-virtualized` :) so I can close this. 👍
