### ISSUE TITLE
Deprecate support

### ISSUE THREAD

**Issue by juanpicado** [verdaccio/ui#499]
**Is your feature request related to a problem? Please describe.**

~In the next release we support `npm deprecate`~, this information will be available in the UI
https://github.com/verdaccio/verdaccio/pull/1842

The latest version already contains deprecated suppport via CLI

**Describe the solution you'd like**

I'd like be able to display a deprecated package visually. 

**Describe alternatives you've considered**

Let's brainstorm here.

Example of deprecated package: https://www.npmjs.com/package/request

**Comment by frank-dspeed** [comment]
@juanpicado The Main Problem that comes up is!
Befor this implamentation we could assume that data will not change npmjs.org will be consistent package meta don't changes.

After this implamentation we deal with the fact that the deprecation status can change after we have fetched a copy of the package.

 We need to implament some form of last checked State from the upstream
some kind of extra fild lastChecked its not allowed to get added to the package.info
 We need to handle user Permissions will it be possible to deprecate packages that you don't manage for example in a use case where a user installs this as proxy and don't registers users he will fetch packages that he could deprecate some how?
 Should this inhire pull the NPM Or Upstream Registry deprecation meta infos
 Schould this also run deprecate against the upstream Registrys?
 When a NPM Package is not deprecated but we have a deprecated version?
 When a NPM Package is deprecated but we have a none deprecated version?
 deprecation state needs sync with upstream registrys
 plugin authority-registry
Current Standard behavior ask upstream only if we don't got infos
but stores indipenden deprecation messages.if present deprecation behavior needs to be set explizit if it should inhire from source registry or not
 plugin proxy-registry
if we know we run as a offline proxy
if we know we are a additional cache for npm

**Comment by priscilawebdev** [comment]
closing this as it's duplicated https://github.com/verdaccio/ui/issues/67
