### ISSUE TITLE
The search input in home page is narrow 

### ISSUE THREAD

**Issue by zhuqingguang** [verdaccio/ui#559]
- [x] I'd be willing to implement the feature

 I'm sometimes frustrated when i open homepage and click the blank area on the right of `search input` but it can not focus
the `search input`:
![image](https://user-images.githubusercontent.com/24694223/94529477-5f170600-026c-11eb-99f0-1366ec928dae.png)
As the blank area is a bit wider but unreactive, I think it's not friendly for user.
![image](https://user-images.githubusercontent.com/24694223/94529615-88379680-026c-11eb-9a3f-b7ea03f1e1e8.png)

**Comment by juanpicado** [comment]
go ahead :) I'd make sure this goes to the next release.

**Comment by zhuqingguang** [comment]
@juanpicado   Hi~The css of the `search input div` has a `max-width: 393px;`. The easiest way to change the ui is remove this line. But it's a tremendous change to the ui .   And another way is to add a click event handler to the empty area on the right of the input. 

 In your  opinion whick one is more reasonable ？

![image](https://user-images.githubusercontent.com/24694223/94929080-2f2f6300-04f7-11eb-9382-24a5a9079719.png)
![image](https://user-images.githubusercontent.com/24694223/94928184-df03d100-04f5-11eb-9723-b5e2f7fb4bcd.png)

**Comment by priscilawebdev** [comment]
@zhuqingguang if you remove the maxWidth it should be wider and it will not cause problems.

**Comment by zhuqingguang** [comment]
> @zhuqingguang if you remove the maxWidth it should be wider and it will not cause any problems 😉

I have test the ui in dev mode and it change nothing except that it makes search input wider.
But as it's a big change, i'm not very confident that it will not make users confused  😂😂 .
