### ISSUE TITLE
No Package Published Yet title is too big

### ISSUE THREAD

**Issue by juanpicado** [verdaccio/ui#578]
- [ ] I'd be willing to implement a fix

**Describe the bug**

The title is too big when there is no packages installed. 

![Screenshot from 2020-10-11 18-26-13](https://user-images.githubusercontent.com/558752/95684086-5a007200-0bef-11eb-808d-753a73ca67df.png)

**Comment by rokkoo** [comment]
Can I do it? 😊

**Comment by juanpicado** [comment]
All yours
