### ISSUE TITLE
Forgot password?

### ISSUE THREAD

**Issue by guatedude2** [verdaccio/ui#59]
**Is your feature request related to a problem? Please describe.**
I think it would be great to have a forgot password on the UI. It's nice to be able to recover accounts since we dont typically remember what password was set up during npm login.

**Describe the solution you'd like**
A user can go to the UI, click on the "forgot password?" link bellow the login form. It pops up a form with an email field and a submit button. The form then sends an email to the said email as long as it's tied to an account it will send a link to recover the password. On the email, when clicking on the link it takes the user back to the verdaccio website `/recover?token=HASH`, and a form should show up with two fields and a submit button, "new password" and "confirm password". When the submit is clicked a confirmation message should appear and the user is redirected to the login.

**Describe alternatives you've considered**
I considered change password, but this doesn't work because you wouldn't know your existing password in order to change it.

**Additional context**
Checkout npm's "forgot password" page https://www.npmjs.com/forgot

**Comment by juanpicado** [comment]
cc: @verdaccio/core-team thoughts?

**Comment by DanielRuf** [comment]
I think currently there is no connection between email addresses and logins. At least I see no normal database for such workflows.

> The form then sends an email to the said email as long as it's tied to an account it will send a link to recover the password

This would require a mail server (via SMTP Auth etc).

**Comment by DanielRuf** [comment]
I think this should be done by sysadmins (password reset). Currently we just store username and password.

At least as the logins are often just needed for publishing packages and if someone forgets the password then I would say there are other issues with the internal password policy and management.

If we would like to integrate this feature it would require many big changes (secure token generation, new routes and pages, secure mail server connection, magic link generation, securely storing email addresses, secure password forgot feature to prevent credential stuffing, ...).

**Comment by DanielRuf** [comment]
Relevant: https://github.com/verdaccio/ui/issues/1

**Comment by juanpicado** [comment]
> The form then sends an email to the said email as long as it's tied to an account it will send a link to recover the password. 

As @DanielRuf pointed out, it is not double. npmjs is a complex microservice architecture which cannot be emulated with a small npm package. 

sorry @guatedude2 what you are requesting is not doable.

**Comment by guatedude2** [comment]
Thanks for looking into it
