### ISSUE TITLE
HMR not working

### ISSUE THREAD

**Issue by DanielRuf** [verdaccio/ui#62]
**Describe the bug**
Hot Module Reloading does not work. It seems some state is missing when the devserver reloads the components.

**To Reproduce**
1. Start the webserver and the ui
2. Open the browser at http://localhost:4872/-/web/detail/any-package
3. Change the content of the `DetailContainer` component

**Expected behavior**
No error and an updated component.

**Screenshots**
![Bildschirmfoto 2019-05-21 um 12 06 43](https://user-images.githubusercontent.com/827205/58087633-3800ec80-7bc1-11e9-8af2-bfdd52ffd9d8.png)

```
(RouterApp, in Router (created by RouterApp)) TypeError: Cannot read property 'logoUrl' of undefined

(RouterApp, in Route (created by RouterApp)) TypeError: Cannot read property 'isUserLoggedIn' of undefined
```

**Comment by juanpicado** [comment]
@DanielRuf 

**Issue**:
As far I could see the error is, the Context API state is being lost so, that leads to that issue.

**Possible Solution:**

This "solves" the issue https://github.com/gaearon/react-hot-loader/issues/1184#issuecomment-465292148 

Comment out this https://github.com/verdaccio/babel-preset/blob/master/lib/builder.js#L76

I also updated 

```
  "devDependencies": {
     "@commitlint/cli": "7.5.2",
     "@commitlint/config-conventional": "7.5.0",
+    "@hot-loader/react-dom": "16.8.6",
     "@material-ui/core": "3.9.0",
     "@material-ui/icons": "3.0.2",
     "@octokit/rest": "16.23.2",
@@ -71,7 +72,7 @@
     "react-autosuggest": "9.4.2",
     "react-dom": "16.8.3",
     "react-emotion": "9.2.12",
-    "react-hot-loader": "4.7.1",
+    "react-hot-loader": "4.8.7",
     "react-router": "4.3.1",
     "react-router-dom": "4.3.1",
     "resolve-url-loader": "3.0.1",
```
Perhaps that also helps. 

The result is the page refresh without a full hot reload, but it works and at least we do not see that weird error.

**Comment by DanielRuf** [comment]
Seems to work with this proposed solution.

**Comment by juanpicado** [comment]
@DanielRuf if you ask me, I'd prefer a semi working version of this that completely broken. I think we can override the `.babelrc` conf without touch the `babel-preset` package.

**Comment by DanielRuf** [comment]
Sounds good. We could do this with `patch-package`. I have applied the changes to my local `@verdaccio/ui` setup using it.

**Comment by juanpicado** [comment]
@DanielRuf can we close this?

**Comment by DanielRuf** [comment]
Not sure if this is resolved now without applying custom patches. I have to test it again.

Were there relevant changes?
