### ISSUE TITLE
Feat: Deprecated package

### ISSUE THREAD

**Issue by honzahommer** [verdaccio/ui#67]
Show deprecate message if version object has deprecated property. Related PR https://github.com/verdaccio/verdaccio/pull/1308.

- https://www.npmjs.com/package/jade
- https://registry.npmjs.org/jade

**Comment by JayaKrishnaNamburu** [comment]
Hey @juanpicado I would like to take a shot at this, once the API endpoint is completed.

**Comment by juanpicado** [comment]
@JayaKrishnaNamburu that's cool, in the meantime, could you make small mockup how should looks like from your perspective?

**Comment by JayaKrishnaNamburu** [comment]
@juanpicado you mean a static design implmentation?

**Comment by juanpicado** [comment]
Before developing the UI user interface, this https://github.com/verdaccio/verdaccio-balsamiq was a good start, so all we had a clear picture of what we had to do. I'm not asking for a complete mock up, but you might just modify the HTML with dev tools to emulate where and how we might display a package is deprecated.

**Comment by JayaKrishnaNamburu** [comment]
Got it, sure will do that and update 🙂👍

**Comment by JayaKrishnaNamburu** [comment]
![Deprecated Package Verdaccio](https://user-images.githubusercontent.com/11075561/59326442-34660e80-8d04-11e9-882c-1edf0654774e.png)

@juanpicado just tried this, please share your suggestions. I will update them.

**Comment by juanpicado** [comment]
Allow me to explain to you how the `deprecate` works.  Please notice our npmjs page https://www.npmjs.com/package/verdaccio and click on Versions, then click on **show deprecated versions**, then scroll down and you will notice a **read** label. The unique you can `deprecate` is versions, packages only can be removed.

Furthermore, deprecate also has a message that might be useful for you, check the docs https://docs.npmjs.com/cli/deprecate

I hope this gives you more fresh ideas.

**Comment by detj** [comment]
I just deprecated a package and realised Verdaccio does not show the deprecated message upfront.  And then landed on this issue. 😄 

@juanpicado As per the syntax `npm deprecate <pkg>@[<version>] <message>`, `version` is optional. So, if a package is deprecated without version it implies all versions are marked deprecated? Correct me, if I'm understanding this wrong.

And, so, if all versions of a package have been deprecated does it make sense to show a banner upfront on the package detail page with appropriate danger color to grab the user's attention?
