### ISSUE TITLE
Failed to load all packages after login

### ISSUE THREAD

**Issue by coolsp** [verdaccio/ui#72]
**Describe the bug**
Non-public packages not included in the package-list after login.

**To Reproduce**
1. Load the UI in a browser
2. You can see the public packages available to all
3. Login
4. Package list still the same, not included non-public packages I can access

**Expected behavior**
A package list containing all packages I can access.

> I have a PR ready solving this issue

**Comment by DanielRuf** [comment]
Hi @coolsp,

Thanks for reporting the issue and especially for providing the PR.
