### ISSUE TITLE
Replace node-sass by emotion

### ISSUE THREAD

**Issue by juanpicado** [verdaccio/ui#78]
**Is your feature request related to a problem? Please describe.**

We want to remove `node-sass` from our code base, actually, we have 2 CSS libraries living in our code base. 

**Describe the solution you'd like**
I want to migrate all to `emotion` and reduce dependency from `sass`.

**Describe alternatives you've considered**

We are considering `material-ui` styles as an alternative to keep all in the same world, but that will be under discussion.

**Additional context**

List of current files using `scss` files.

<img width="1016" alt="Screen Shot 2019-06-24 at 8 59 59 PM" src="https://user-images.githubusercontent.com/558752/60044650-1ebcf580-96c3-11e9-8296-406e9dc4ba0b.png">

**Comment by griffithtp** [comment]
If there is no takers, I would be keen to give it a try?

**Comment by juanpicado** [comment]
All yours @griffithtp , I think nobody is actively working on this as far I know.

**Comment by griffithtp** [comment]
@juanpicado we might also need to upgrade to emotion v10 here and it has some breaking changes I am looking at to resolve.
Also, snapshot testing doesn't seem to work using the jest-emotion serializer for components that already has a render method, which is a shame; will look into further config settings.
If anyone has experienced a similar issue, do let us know?

**Comment by juanpicado** [comment]
I would wait for that upgrade, we have been considering use https://material-ui.com/es/styles/basics/ instead which is built-in in material-ui. @priscilawebdev suggested to  use it, back then was in alpha so we stopped, but now it is stable.

**Comment by griffithtp** [comment]
@juanpicado can this be closed and resolved now? 😃

**Comment by juanpicado** [comment]
Thanks @griffithtp :-) you are right !
