### ISSUE TITLE
Can be on the right under the infos column under the Repository Option plus a button to copy the address?

### ISSUE THREAD

**Issue by godkun** [verdaccio/ui#81]
**Is your feature request related to a problem? Please describe.**
Now the Repository under the right infos column. The option doesn't have a button to copy the address, so when I want to copy the ssh address, I can only click into a new page to see the full address.

The current page is like this：
![image](https://user-images.githubusercontent.com/26134303/60419255-6a1d5980-9c17-11e9-9e0e-de065a85b6e5.png)

I hope that you can add a copy address button on the right side as shown in the figure：
![image](https://user-images.githubusercontent.com/26134303/60419045-009d4b00-9c17-11e9-9c51-248cd53a6a99.png)

**Describe the solution you'd like**
I want the Repository under the right infos column. There can be a button to copy the address to the right of the option, so I don't have to click into a page every time to copy the address.

**Comment by juanpicado** [comment]
Hi @godkun 

I guess you are still using Verdaccio 3 as far I can see.

I'd suggest @godkun you move to Verdaccio 4 we have that feature already.

eg: https://registry.verdaccio.org/-/web/detail/jquery

**Comment by godkun** [comment]
enen, sorry, it’s version 3.0, I will rise to 4.0 later. 
Thank you.
