### ISSUE TITLE
Crashing while trying to view readme

### ISSUE THREAD

**Issue by NathanaelA** [verdaccio/ui#83]
**Describe the bug**
Using v4.04 -
Just clicking on a link to view the readme throws the following error in the browser (both brave and firefox):
```
vendors.b6891b53f2830d5ac3cb.js:46 Invariant Violation: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Btype%2C%20url%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.   
```

Crashing Browser side Code:
```
   function fo(e, t) {
        "textarea" !== e.type && a("31", "[object Object]" === Object.prototype.toString.call(t) ? "object with keys {" + Object.keys(t).join(", ") + "}" : t, "")
    }
```
The e.type was element of type "span".  
The t = was  the license section from the package.json: 
```
"license": {
    "type": "scoped",
    "url": "https://git.master.technology/scoped/somename-month-calendar/blob/master/LICENSE"
  },
```

**To Reproduce**
1. I logged in via npm 
2. I uploaded a single @scoped package
2. Uplink is disabled in config
3. I navigated to the main page (that lists plugins)
4. I clicked the package name to see the readme  (i.e. link is `/-/web/detail/@scoped/somename-month-calendar`
5. See error

**Expected behavior**
I assume I would see the package readme.

**Configuration File (cat ~/.config/verdaccio/config.yaml)** 

I removed the other package sections; as I only need this one.   (No uplink active), no other packages.  The rest of the config except for the listen is stock.

```
packages:
  '@scoped/*':
    # scoped packages
    access: $all
    publish: $authenticated
```

**other info**
All http requests were status 200 or 304 on both browser and console on server.

**Comment by NathanaelA** [comment]
@juanpicado - I figured out what is crashing it.   I was on the right trail last night.  ;-)    The License section is not liked by the front end.    
```
"license": {
    "type": "scoped",
    "url": "https://git.master.technology/scoped/somename-month-calendar/blob/master/LICENSE"
  },
```

The front end is expecting this to be a string...   Me switching this package to:
`"license": "any string"`
Allowed the frontend to work.     Unfortunately, the license format I have listed above is very common...

I'll look around; but if you are online and can point me towards where this code is located in the front end -- I'll create a PR for it...

**Comment by NathanaelA** [comment]
The issue I believe can be fixed here:
https://github.com/verdaccio/ui/blob/a0f0c80e2e8c635bb7dcb6dc2a7884e6a52bf3b0/src/components/Dist/Dist.tsx#L52

```
 private renderDist = (packageMeta: PackageMetaInterface) => {
    let { dist, license } = packageMeta && packageMeta.latest;
    // Check to see if License is valid, if valid -- check to see if it is an object and grab the key...
    license = license ? (license.type ? license.type : license) : "";

    return (
      <List subheader={<Heading variant="subheading">{'Latest Distribution'}</Heading>}>
        <DistListItem>{this.renderChips(dist, license)}</DistListItem>
      </List>
    );
  };
}
```

**Comment by DanielRuf** [comment]
Hi @NathanaelA,

Not sure where the license field is an object normally.
Also I do not know if licence check tools properly detect the (SPX) licences.

Can you show some real-world examples?

**Comment by DanielRuf** [comment]
Hi @NathanaelA,

Not sure where the license field is an object normally.
Also I do not know if licence check tools properly detect the (SPDX) licences.

Can you show some real-world examples?

**Comment by DanielRuf** [comment]
According to https://docs.npmjs.com/files/package.json#license the object style is deprecated but we may still have to support it.

> Some old packages used license objects or a “licenses” property containing an array of license objects:

> Those styles are now deprecated. Instead, use SPDX expressions, like this:

**Comment by DanielRuf** [comment]
I would suggest doing this with if / else if / else.

```
if (typeof license === "object" && license.type) {
return license.type;
} else if (typeof license === "string") {
return license;
} else {
return "";
}
```

Ternary is not great for such more complex checks. And type checking is important.

**Comment by NathanaelA** [comment]
@DanielRuf - To be honest; every single one of my about ~40 plugins have that style.   I'll start fixing them as I upgrade them.  (Thanks for the npm link!).    I honestly was unaware that it has been considered invalid -- I was taught using that apparently now invalid style. :grinning:    In fact I would venture a guess about 10%-30% of the 1000ish plugins I'm tracking probably have that style...       

 Anyways; even if it was just a single plugin -- having the whole interface crash is a significantly bad thing even if it is caused by what is now considered bad data...   At worst case I would expect the license pip to not render; not crash the whole interface...

As for Ternary; I don't disagree; just wanted to drop something quick to fix the issue.   In fact if we are being proper; I would change that to be something like:
```
if (license == null) { return ''; }
else if (license && license.type) { return license.type; }
else return license;
```
Your code translates to this if license is null...
`typeof null === 'object' && null.license === crash...`
