### ISSUE TITLE
Show latest version on Package Sidebar

### ISSUE THREAD

**Issue by detj** [verdaccio/ui#84]
**Is your feature request related to a problem? Please describe.**
One of the common questions anyone has while checking out a package on a registry is what version will get installed when they install the package. Verdaccio 3.x.x showed the latest package version on the right side, but Verdaccio 4.x.x shows all the package versions under the "VERSIONS" tab.

**Describe the solution you'd like**
Accommodating latest version in the Package Sidebar would quickly give users the information they need about version of the package.

**Describe alternatives you've considered**
I thought about the alternatives, like showing the version in header, or in the VERSIONS tab. All the alternative solutions did not make much sense to me.

**Additional context**
Does it makes sense to show the version under "Latest Distribution" section in Package Sidebar? Or a new section? Also, not sure if this issue relates to #21

**Comment by juanpicado** [comment]
I support this. We display it in the Frontend but do not on detail page.

**Comment by karthick-manoharan** [comment]
Taken. Will raise a PR in a day or two

**Comment by cowchimp** [comment]
Hi.
Long time user, first time contributor 😄

I want to help with this, but just to make sure:
If I understand correctly, the issue states that the latest package version is missing in the "package sidebar".
But I do see the latest package version on the right in the README tab.
Is this not where it's claimed to be missing? Is it missing somewhere else?
Thanks!

![image](https://user-images.githubusercontent.com/1131004/65988064-cc445f80-e48f-11e9-9734-bbb322bfd819.png)

**Comment by juanpicado** [comment]
I think you are right :D I did it myself, I think this ticket is outdated. I will close it. 👍

**Comment by masterkain** [comment]
what is "Latest Distribution" ?
