### ISSUE TITLE
chore: Update @material-ui@4.2.x

### ISSUE THREAD

**Issue by priscilawebdev** [verdaccio/ui#87]
Update Material UI dependencies with the latest versions.

the dependencies are: 

 "@material-ui/core": "3.9.3",
 "@material-ui/icons": "3.0.2",

**Comment by sergiohgz** [comment]
:thinking: I’ve just remembered that MUI have been updated to 4. The exact versions are:
@material-ui/core -> 4.2.0
@material-ui/icons -> 4.2.1

Also, @material-ui provides a package called @material-ui/types, with Ts types (with version 4.1.1, but I always used types provided in @material-ui/core). Should we migrate to that package? What do you think @priscilawebdev ?

**Comment by priscilawebdev** [comment]
Hi @sergiohgz ...yes I am going to update to the latest versions...There are some breaking changes...so I need to be careful...regarding the types....we are already using @types/material-ui so I think we can leave like that...

**Comment by sergiohgz** [comment]
Take care when upgrading to v4, @types/material-ui might be incompatible with @material-ui v4. That types haven’t been updated for 5 months, so if you find incompatibilities, take a look in @material-ui/types (also, if you find easy to move to this package, it could be great 🙂 )

**Comment by priscilawebdev** [comment]
I will check it out..thank you for the tipp 😉

**Comment by juanpicado** [comment]
Please, let us  know how big might be this before start a PR, perhaps we can split this up in some PR.

**Comment by sergiohgz** [comment]
I've just investigated @material-ui/types and they are utilities types. Also, @material-ui/core takes it as dependency, so we don't need to import it explicitly (take a look here https://github.com/mui-org/material-ui/blob/master/packages/material-ui/package.json#L43)

**Comment by sergiohgz** [comment]
Sorry, closed due to ipad issues (I might change it for a new one 😅 ).

@priscilawebdev don’t care about @types/material-ui, we should remove them as @material-ui provides their own types and, I saw, @types/material-ui is a package that links the types provided by @material-ui, so they could be obsolete. Should we open an issue to get rid about it?
