### ISSUE TITLE
The logos has incorrect style

### ISSUE THREAD

**Issue by juanpicado** [verdaccio/ui#89]
**Describe the bug**

We have regression issues due to https://github.com/verdaccio/ui/pull/80

![Verdaccio_-_webpack](https://user-images.githubusercontent.com/558752/60767361-3cbd2980-a0b7-11e9-9d64-d3e9cb2c2fd7.png)

The issue seems we forgot to remove some quotes https://github.com/verdaccio/ui/pull/80/files#diff-2780c4d0882ad10abae71aa33af34c7bR147

It affects loading logo and header logo.

Issues

![Screen Shot 2019-07-07 at 1 02 02 PM](https://user-images.githubusercontent.com/558752/60767376-6ece8b80-a0b7-11e9-9fe6-228f36fa1d4e.png)

![Screen Shot 2019-07-07 at 1 01 14 PM](https://user-images.githubusercontent.com/558752/60767370-58c0cb00-a0b7-11e9-93c9-edbf7c541981.png)

**Comment by griffithtp** [comment]
apologies, fix should be in #85 
https://github.com/verdaccio/ui/pull/85/files#diff-2780c4d0882ad10abae71aa33af34c7b

**Comment by juanpicado** [comment]
@griffithtp it is not your fault, my bad, it was introduced here https://github.com/verdaccio/ui/pull/47

**Comment by griffithtp** [comment]
> @griffithtp it is not your fault, my bad, it was introduced here #47

it was actually from PR85; where I mixed up template literals and css object notation.
should be reverted now from that remove sass PR but PR94 has the better fix with logo size :)

**Comment by sergiohgz** [comment]
Closed #89 via #94

**Comment by juanpicado** [comment]
Thanks @sergiohgz great job.
