### ISSUE TITLE
[feature] Readme.md with syntax highlight

### ISSUE THREAD

**Issue by cesco69** [verdaccio/ui#9]
**Is your feature request related to a problem? Please describe.**
Verdaccio doesn't show markdown code block with syntax highlight based on code type like github/gitlab. eg. the following code:

```javascript
function foo(bar){
    return bar;
}
```

on verdaccio is shown in grayscale:

```
function foo(bar){
    return bar;
}
```

**Describe the solution you'd like**
Implements a syntax highlighter, eg.: https://highlightjs.org/

**Comment by juanpicado** [comment]
Duplicated https://github.com/verdaccio/ui/issues/3
