### ISSUE TITLE
Investigate how to remove !important in styles

### ISSUE THREAD

**Issue by sergiohgz** [verdaccio/ui#95]
`!important` CSS keyword carries several behaviours in accessibility, so we have to try avoid their usage as much as we can.

We could try to make important things by repeating CSS class name instead, as commented in the PR referenced below.

_Originally posted by @sergiohgz in https://github.com/verdaccio/ui/pull/85_

**Comment by juanpicado** [comment]
From my favorite CSS book ever -> https://www.manning.com/books/css-in-depth

![Screen Shot 2019-07-10 at 9 51 53 AM](https://user-images.githubusercontent.com/558752/60950960-65803180-a2f8-11e9-93f3-c2e556bcc0db.png)

**Comment by griffithtp** [comment]
Since I've adopted the BEM naming convention I have not come across a scenario where I've had to resolve using `!important` with clearly defined components.
With css-in-js though, I'd be very curious what different approach would be if applicable at all since classnames are hashed when bundled 🤔

**Comment by juanpicado** [comment]
We need BEM or similar approach for each section or component, in case you guys are not aware we have some E2E testing at Verdaccio which looks for Ids or classes for some smoke UI test and check small things. Thus, we need to create a strategy for different sections and perhaps do not rely on IDs as we do now.

**Comment by priscilawebdev** [comment]
@sergiohgz I did some research and we have the `!important` tag only here:

![image](https://user-images.githubusercontent.com/29228205/71698311-641d5680-2dbb-11ea-8140-92a9451e149c.png)


this piece of code is not even used anymore ... we can safely remove it :)
