### ISSUE TITLE
Unify Emotion CSS definition format

### ISSUE THREAD

**Issue by sergiohgz** [verdaccio/ui#97]
We should unify the way we are defining CSS with Emotion, as we are mixing the ways we can define them and we can make some mistakes (as quotes where aren’t needed).

As we can see at [Emotion docs](https://emotion.sh/docs/), there are 2 ways of defining CSS, using **templated strings** syntax or **object** syntax. Here is a sample of the same codeblock in both styles:

##### Templated string syntax
```javascript
<div
  css={
    css`
      background-color: green;
      font-size: 16px;
      padding: 32px;
    `
  }
>
```
##### Object syntax
```javascript
<div
  css={
    css({
      backgroundColor: 'green',
      fontSize: '16px',
      padding: '32px',
    })
  }
>
```

The main difference is easy to view, the **templated string** syntax follows _CSS conventions_ like _hyphens_ to separate words or _semicolons_, while **object** syntax is a simple Javascript object, with _camelCase_ in keys, _commas_ to separate properties and the need of _string values_ (when the value is not another object).

I prefer _object_ syntax as it is nearer to Javascript and it keeps _SoC (Separation of Concerns) principle_, not mixing CSS code in JS files.

I would like to have opinions about before proceed with this task.

cc: @verdaccio/core-team

**Comment by griffithtp** [comment]
It'd feel more natural to use template literals for me because in the end it is CSS.
However, it does not warn you where you've made a typo which introduced the Logo style bug recently having accidently put margins in quotes (sorry 😅)
Unless we can apply linting rules in css template string, object styles might be a safer option.
Decision like this is tougth and at the end of the day we should be able to output rendered styles we clearly see from the snapshot test files.

**Comment by sergiohgz** [comment]
First of all, I have to say that you don't have to apologize about introducing a typo, nobody has dead for it :smiley:. In the PR fixing that quotes, I saw another extra quotation in Login that I don't know when it was introduced but, IMHO, I don't feel very comfortable with string templates as code written inside is not JS/TS.

Of course, you are right @griffithtp in the term that at the end it's CSS, but in the real end. There is a way to differentiate both syntaxes, templated strings are CSS written in JS files and objects are JS that transforms to CSS. This remembers me about components templating in AngularJS, they are just HTML written in JS files, so that doesn't accomplish SoC principle.

I am trying to migrate some patterns from templated strings to objects and I feel very comfortable because I don't need to update snapshots, as the CSS class hash is the same. Also, I see that this way we can remove StyleLint tool, because we will delegate it to ESLint.

**Comment by juanpicado** [comment]
> Unless we can apply linting rules in css template string, object styles might be a safer option.

@griffithtp we use linting for CSS-JS, but it is not perfect, lack of features, hard to rely on it.

I'd like to have objects, we rely on Material-UI and at some point we have to study how hard is uses https://material-ui.com/es/styles/basics/ instead or emotion, I'd like to have less dependencies as possible (each dependency is x10 change to have a external bug or security warning).

> I am trying to migrate some patterns from templated strings to objects and I feel very comfortable because I don't need to update snapshots, as the CSS class hash is the same. Also, I see that this way we can remove StyleLint tool, because we will delegate it to ESLint.

@sergiohgz I think is the way to go, small PR so we can minimize visual bugs are not able to catch with unit test.

**Comment by sergiohgz** [comment]
@juanpicado Of course, I am going to look what I have advanced and tomorrow I will make a small PR to start discussion

**Comment by griffithtp** [comment]
@juanpicado @sergiohgz 
Hey guys I may have found a case where template string might be as good as Object
From https://github.com/verdaccio/ui/blob/master/src/components/Package/styles.ts#L135~L144
```
export const TagContainer = styled('span')`
  && {
    margin-top: 8px;
    margin-bottom: 12px;
    display: block;
    @media (max-width: ${breakpoints.medium}px) {
      display: none;
    }
  }
`;
```
I am not too sure how we could define `@media` queries as object key here

**Comment by juanpicado** [comment]
@griffithtp we might wait for material 4 and styles, I think they do support media queries with objects, I'm not 100% sure.

**Comment by antoinechalifour** [comment]
Any news regarding this issue ? As of today it seems the project is using at the same time:

- the `css({})` syntax from **emotion**
- the `css``` syntax from **emotion**
- `styled('tag')``` from **react-emotion**

It would be great to unify those. Please note that react-emotion is not relevant anymore, and `@emotion/styled` should be used instead https://yarnpkg.com/en/package/@emotion/styled

I'd really like to help with the migration :)

**Comment by DanielRuf** [comment]
Hi @antoinechalifour,

no news so far. There are things with a higher priority on our list.
